# Site settings
title: "Visualization in Data Science (VDS at ACM KDD and IEEE VIS)"
email: "vds@ieeevis.org"
description: "Visualization in Data Science (VDS at ACM KDD 2022 and IEEE VIS 2022)"
baseurl: "/2022"
url: "http://www.visualdatascience.org/"
conferenceshort: "VDS 2022"
conferencedate: "TBD" 

deadline_submission:  "Thur., <s>May 26th</s> June 2nd, 2022, 5:00 pm PDT"
deadline_notification: "Mon., June 20th, 2022, 5:00 pm PDT"
deadline_submission_vis:  "Thur., <s>July 7th</s> July 14th, 2022, 5:00 pm PDT"
deadline_notification_vis: "Thur., August 25th, 2022, 5:00 pm PDT"
event_date: "August 14 (Tentative)" 
event2_date: "TBD"

# Build settings
markdown: kramdown

collections:
- talks

