# Site settings
title: "Visualization in Data Science (VDS at ACM KDD and IEEE VIS)"
email: "vds@ieeevis.org"
description: "Visualization in Data Science (VDS at ACM KDD 2022 and IEEE VIS 2022)"
baseurl: "/2022"
url: "http://www.visualdatascience.org/"
conferenceshort: "VDS 2022"
conferencedate: "TBD" 

deadline_submission:  "Thur July 7, 2022, 5:00 pm PDT"
deadline_notification: "Thur, August 25, 2022, 5:00 pm PDT"
event_date: "TBD" 
event2_date: ""

# Build settings
markdown: kramdown

collections:
- talks

