# Site settings
title: "Visualization in Data Science (VDS at ACM KDD and IEEE VIS)"
email: "vds@ieeevis.org"
description: "Visualization in Data Science (VDS at ACM KDD 2022 and IEEE VIS 2022)"
baseurl: "/2022"
url: "http://www.visualdatascience.org/"
conferenceshort: "VDS 2022"
conferencedate: "Oct. 24 (VIS), Aug. 14 (KDD)2022  (US West) " 

deadline_submission:  "<s>Thur, May 20th, 2022</s><br> <s>Thur, May 27th, 2021</s>"
deadline_notification: "<s>Thur, June 10th, 2022</s><br> <s>Thur, June 17th, 2021</s>"
event_date: "<s>August 14, 5pm - 9pm (US West) / August 15, 8am - 12pm (Singapore), 2022</s>" 
event2_date: "Oct 24, 8am - 12am (US Central), 2022"

# Build settings
markdown: kramdown

collections:
- talks

